version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    image: php:8.0-fpm-alpine
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - mysql

  # db:
  #   image: mysql:5.7
  #   ports:
  #     - 13306:3306
  #   volumes:
    #   - ./mysql/data:/var/lib/mysql
    # environment:
    #   MYSQL_ROOT_PASSWORD: secret
  
  mysql:
    build: ./mysql/    #Dockerfileからビルドすることを示す
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/db:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    image: mysql:latest # イメージの名前
    environment:
      MYSQL_ROOT_PASSWORD: secret   #コンテナ内のMySQLを起動する際のパスワードを設定
      MYSQL_DATABASE: quizy_database
      MYSQL_USER: rena
      MYSQL_PASSWORD: secret
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
       - 3306:3306
    

    # phpmyadmin:
    #   image: phpmyadmin/phpmyadmin:latest
    #   ports:
    #     - 8888:80
    #   depends_on:
    #     - db
